export const uploadSettings = {
  'uploadSettings.screenshotsTitle': 'Screenshots',
  'uploadSettings.screenshotsDescription': 'Applied to the next upload prepared, not retroactive on ones already ready.',
  'uploadSettings.screenshotCountLabel': 'Screenshot count',
  'uploadSettings.screenshotCountDescription': 'Equally spaced frames, excludes the first/last 5% of the duration.',
  'uploadSettings.tonemapLabel': 'Tonemap HDR in screenshots',
  'uploadSettings.tonemapDescription':
    'Converts HDR→SDR (mobius algorithm) before capturing screenshots — without it, an HDR source looks washed out/dark once interpreted as SDR.',
  'uploadSettings.descriptionTitle': 'Description',
  'uploadSettings.descriptionHeaderLabel': 'Description header',
  'uploadSettings.descriptionHeaderHelp':
    'Text (e.g. BBCode) prepended to the description generated by the tracker template — leave empty to add nothing.',
  'uploadSettings.descriptionHeaderSaved': 'Header saved.',
  'uploadSettings.saveHeaderButton': 'Save header',
  'uploadSettings.imageHostsTitle': 'Image hosts',
  'uploadSettings.imageHostsDescription':
    "Priority and status on the left, API keys on the right — the first enabled host is tried, if it fails the next one is used. Imgbox and Pixhost don't require one.",
  'uploadSettings.noApiKeyRequired': 'no api_key required',
  'uploadSettings.priorityOrderLabel': 'Image host priority order',
  'uploadSettings.priorityOrderHelp': 'Drag to reorder — the first one is tried, if it fails the next one is used.',
  'uploadSettings.priorityOrderSaved': 'Priority order saved.',
  'uploadSettings.dragToReorder': 'Drag to reorder {label}',
  'uploadSettings.disable': 'Disable',
  'uploadSettings.hostDisabled': '{host} disabled.',
  'uploadSettings.hostEnabled': '{host} enabled.',
} as const
